spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
