services:
  redis:
    container_name: yapp_redis
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - app-network

  app:
    image: yapp
    build:
      context: .
      dockerfile: dockerfile-prod
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
      - redis
    networks:
      - app-network

networks:
  app-network: