services:
  postgresql:
    container_name: yapp_postgresql
    image: postgres:alpine
    environment:
      POSTGRES_DB: yapp
      POSTGRES_USER: yapp
      POSTGRES_PASSWORD: yapp
    ports:
      - '5432:5432'
    restart: always
    networks:
      - yapp-network

  redis:
    container_name: yapp_redis
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - yapp-network

networks:
  yapp-network:
    driver: bridge