spring:
  application:
    name: yapp
  profiles:
    active: local
    group:
      local: domain-local, cloud-local, spotify-local
      dev: domain-dev, cloud-dev, spotify-dev
      prod: domain-prod, cloud-prod, spotify-prod
