spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  docker:
    compose:
      enabled: false

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    region: ${REGION}
    s3:
      bucket: ${BUCKET}
    stack:
      auto: false