spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      stop:
        command: down
        timeout: 1m
  security:
    user:
      name: user
      password: password
  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    region: ${REGION}
    s3:
      bucket: ${BUCKET}
    stack:
      auto: false
