name: ShowPot-Dev-CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Copy Secrets
        env:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          REGION: ${{ secrets.AWS_REGION }}
          BUCKET: ${{ secrets.AWS_BUCKET }}
        run: |
          echo "cloud.aws.credentials.accessKey: $ACCESS_KEY" >> ./app/src/main/resources/application-cloud-dev.yml
          echo "cloud.aws.credentials.secretKey: $SECRET_KEY" >> ./app/src/main/resources/application-cloud-dev.yml
          echo "cloud.aws.region: $REGION" >> ./app/src/main/resources/application-cloud-dev.yml
          echo "cloud.aws.s3.bucket: $BUCKET" >> ./app/src/main/resources/application-cloud-dev.yml

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

      - name: Backend CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          title: ✅ Backend CI success ✅
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "<@1084774841460215839> <@281597829636423682> ShoPot 이슈 혹은 PR을 확인해주세요!"
          color: 00FF00
          username: showPot-Bot
          avatar_url: ${{ secrets.DISCORD_NOTIFICATION_SUCCESS_AVATAR_URL }}

      - name: Backend CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: ❗️Backend CI failed ❗️
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: FF0000
          username: showPot-Bot
          avatar_url: ${{ secrets.DISCORD_NOTIFICATION_FAILED_AVATAR_URL }}
